// public build — WHITELISTED subset.
// Settles rounded (no raw series); COT from CFTC; ONI from NOAA.
// No Norgate time series, per-contract data, or pack CSVs.
// 2026-09-28 08:31
window.__MD__ = {
  "generated_at": "settle 2026-09-23",
  "pages_present": [
    "cocoa-dashboard.html",
    "coffee-dashboard.html",
    "cotton-dashboard.html",
    "curve_steepness.html",
    "energy-dashboard.html",
    "energy-spread-seasonal.html",
    "gasoil-arb.html",
    "global-balances.html",
    "gold-monitor.html",
    "grains-dashboard.html",
    "hog-spreads-seasonal.html",
    "liquidity-dashboard.html",
    "silver-monitor.html",
    "sugar-dashboard.html"
  ],
  "markets": {
    "ZC": {
      "price": {
        "value": 529.0,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 404097,
        "percentile": 99.7,
        "as_of": "2026-09-22"
      }
    },
    "ZS": {
      "price": {
        "value": 1318.0,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 265159,
        "percentile": 100.0,
        "as_of": "2026-09-22"
      }
    },
    "ZL": {
      "price": {
        "value": 67.2,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 92137,
        "percentile": 91.3,
        "as_of": "2026-09-22"
      }
    },
    "ZW": {
      "price": {
        "value": 708.0,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": -12016,
        "percentile": 68.8,
        "as_of": "2026-09-22"
      }
    },
    "KE": {
      "price": {
        "value": 772.0,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 40635,
        "percentile": 88.5,
        "as_of": "2026-09-22"
      }
    },
    "CC": {
      "price": {
        "value": 5530.0,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": -16406,
        "percentile": 11.9,
        "as_of": "2026-09-22"
      }
    },
    "KC": {
      "price": {
        "value": 276.0,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 15806,
        "percentile": 51.3,
        "as_of": "2026-09-22"
      }
    },
    "SB": {
      "price": {
        "value": 17.8,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 216629,
        "percentile": 91.5,
        "as_of": "2026-09-22"
      }
    },
    "CT": {
      "price": {
        "value": 82.9,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 76182,
        "percentile": 89.8,
        "as_of": "2026-09-22"
      }
    },
    "CL": {
      "price": {
        "value": 92.2,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 101828,
        "percentile": 37.2,
        "as_of": "2026-09-22"
      }
    },
    "GC": {
      "price": {
        "value": 4320.0,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 127389,
        "percentile": 62.2,
        "as_of": "2026-09-22"
      }
    },
    "SI": {
      "price": {
        "value": 65.0,
        "as_of": "2026-09-23"
      },
      "cot": {
        "mm_net": 13309,
        "percentile": 36.3,
        "as_of": "2026-09-22"
      }
    }
  },
  "oni": {
    "value": 1.8,
    "season": "JJA",
    "year": 2026,
    "as_of": "2026-JJA"
  },
  "gold_silver_ratio": {
    "value": 67.8,
    "as_of": "settle 2026-09-23"
  },
  "_public_note": "public whitelist \u2014 settles rounded (nearest $10/1\u00a2/0.1\u00a2 per market), COT from CFTC public feed, ONI from NOAA. No Norgate time series. Regenerated by liquidity_pull.py."
};
