// public build — WHITELISTED subset. Never mirrors the private
// dashboards/dashboard_data.js. Regenerated by liquidity_pull.py
// 2026-09-10 11:15
window.__MD__ = {
  "generated_at": "2026-09-10T11:15:47",
  "pages_present": [
    "liquidity-dashboard.html"
  ],
  "markets": {},
  "oni": null,
  "gold_silver_ratio": null,
  "_public_note": "public whitelist \u2014 regenerated by liquidity_pull.py; not a mirror of the private dashboard_data.js."
};
